CREATE TABLE users(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      login VARCHAR(45),
                      age int NOT NULL check(age > 17),
                      created_at TIMESTAMP default now()
--                       phone_number int NOT NULL CHECK (phone_number REGEXP '^(\\+995\\d{9})|(\\+48\\d{9})|(\\+375\\d{9})|(\\+380\\d{9})|(\\+7\\d{10})$')

);

CREATE TABLE orders(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(45) not null,
                      price int,
                      user_id int REFERENCES users (id) ON DELETE CASCADE
                   );
